age: Age of the patient
clustering: Clustering coefficient of the model
credibility: Credibility of the model
execution software: Execution software
ontologies: Ontologies used
scale: Qualitative scale
